# OPEN AI TAXI 



Import Dependency

In [1]:
import numpy as np
import gym
import random

Create enviroment

In [2]:
env = gym.make("Taxi-v2")
env.render()

+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+



In [3]:
# Here we will create our Q-table , how much state(rows) and actions(column) we need, we need to calculate a_size and s_size
action_size = env.action_space.n
print("Action size", action_size)

state_size = env.observation_space.n
print("state_size", state_size)

Action size 6
state_size 500


Create Q-table

In [4]:
#create Q- table

Q_table =np.zeros([state_size,action_size])
print(Q_table)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


Create Hyperparameter

In [5]:
learning_rate = 0.8   #Learning rate
gamma = 0.99  #Discounting rate

total_train_episode = 50000 # Total_episode is used to train our ALGO
total_test_episode = 100  #total_episode to test our ALGO
maximum_step = 99 #maximum_step an agent can take during episode

#Exploration rate

#As we know the the during exploration epsilon is  very high as we agent start learning epsilon start decreasing

epsilon = 1.0
max_epsilon = 1.0
min_epsilon = 0.01
decay_rate = 0.1



Implementing Q-learning algo

In [6]:
for episode in range (total_train_episode):
    #reset the enviroment
    state = env.reset()
    step = 0
    done = False
    
    for step in range(maximum_step):
        exp_exp_tradeoff = random.uniform(0,1)
        
        # IF this number > greater then epsilon  --> exploitation
        if exp_exp_tradeoff > epsilon:
            action = np.argmax(Q_table[state,:])
            
            #Else doing random choice choice ---> exploration
            
        else:
            action = env.action_space.sample()
            
        #take the action (a) and observe the outcome state(s') and reward r
        new_state, reward , done , info = env.step(action)
        
        # Update Q(s,a):= Q(s,a) + lr [R(s,a) + gamma * max Q(s',a') - Q(s,a)]
        
        Q_table[state,action] = Q_table[state,action] + learning_rate*(reward + gamma *
                                                                      np.max(Q_table[new_state,:]) -Q_table[state,action])
        
        
        # Our new state is state
        
        state = new_state
            
        # If done : finish episode
        if done == True:
            break
            
            # Reduce epsilon (because we need less and less exploration)
            
    epsilon = min_epsilon +(max_epsilon - min_epsilon)*np.exp(decay_rate*episode)
        

In [7]:
#USE Q- TABLE TO PLAY TAXI 

In [8]:
env.reset()
rewards = []


for episode in range(total_test_episode):
    state = env.reset()
    step =0
    done = False
    total_rewards = 0
    
    
    for step in range(maximum_step):
        env.render()
        # Take the action (index) that have the maximum expected future reward given that state
        action = np.argmax(Q_table[state,:])
        
        new_state, reward , done , info = env.step(action)
        
        total_rewards += reward
        
        if done:
            rewards.append(total_rewards)
            #print ("Score", total_rewards)
            break
        state = new_state
env.close()
print ("Score over time: " +  str(sum(rewards)/total_test_episode))

+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+

+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (North)
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (Pickup)
+---------+
|R: | : :G|
| : : : :_|
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : : :_: |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (West)
+---------+
|R: | : :G|
| : :_: : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (West)
+---------+
|R: | : :G|
| :_: : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (West)
+---------+
|R: | : :G|
|_: : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (West)
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (North)
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+

+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+--------

  (West)
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+

+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (East)
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (Pickup)
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : |_: |
|Y| : |B: |
+---------+
  (North)
+---------+
|R: | : :G|
| : : : : |
| : : :_: |
| | : | : |
|Y| : |B: |
+---------+
  (North)
+---------+
|R: | : :G|
| : : : : |
| : :_: : |
| | : | : |
|Y| : |B: |
+---------+
  (West)
+---------+
|R: | : :G|
| : : : : |
| :_: : : |
| | : | : |
|